name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          
      - name: Copy .env
        run: cp .env.example .env
        
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Generate Application Key
        run: php artisan key:generate
        
      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
          
      - name: Execute Tests (Pest)
        run: php artisan test

  deploy:
    name: Deploy to VPS
    needs: test # Job ini baru jalan kalau 'test' sukses
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Hanya jalankan saat push ke main (bukan saat PR)
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: https://manifest-usn.my.id

    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Masuk ke folder project
            cd /var/www/sistem-manifest
            
            # Tarik kode terbaru
            git pull origin main
            
            # Restart docker (jika ada perubahan)
            docker compose up -d --build
