name: Deploy to Production

on:
  push:
    branches:
      - main # Akan berjalan otomatis setiap ada push ke branch main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    # Bagian 'environment' inilah yang akan memunculkan menu Deployments di GitHub
    environment:
      name: production
      url: https://manifest-usn.my.id

    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Masuk ke folder project
            cd /var/www/sistem-manifest
            
            # Tarik kode terbaru
            git pull origin main
            
            # Restart docker (jika ada perubahan)
            docker compose up -d --build
